server:
  port: 8084
spring:
  application:
    name: billing-service
  config:
    import: optional:consul://, vault://
  cloud:
    vault:
      token: hvs.Y2oivE7ThzyA8PfbAXN3LWfm
      scheme: http
      kv:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
