server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/madioubah/Documents/projets/java/spring-boot/micro-service-using-consul/config-repo
